- name: install xorg
  become: yes
  apt: name={{item}}
  with_items:
    - xorg
    - xinput

- name: create xorg.conf.d
  become: yes
  file:
    path: "/etc/X11/xorg.conf.d"
    state: directory

- name: setup intel graphics
  become: yes
  copy:
    src: "20-intel.conf"
    dest: "/etc/X11/xorg.conf.d/20-intel.conf"
